apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-secrets
  namespace: platform
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/turbo-rag/secrets/openai-api-key/versions/latest"
        path: "openai-api-key"
