image:
  tag: ""

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: ingestion-sa-prod@turbo-rag.iam.gserviceaccount.com

env:
  - name: GCP_PROJECT
    value: turbo-rag
  - name: PUBSUB_SUBSCRIPTION
    value: ingestion-uploads-sub
  - name: PUBSUB_DLQ_SUBSCRIPTION
    value: ingestion-uploads-dlq-sub
  - name: PREFECT_API_URL
    value: http://prefect-server.prefect.svc.cluster.local:4200/api
  - name: PREFECT_DEPLOYMENT_NAME
    value: ingest-document/ingest-document
  - name: DISPATCHER_MAX_CONCURRENT
    value: "2"
  - name: DISPATCHER_ENABLED
    value: "true"
